### ISSUE TITLE
manuscript and code discrepancy

### ISSUE THREAD

**Issue by arnabbandyopadhyay** [moritzplatz/covid_IFR_Lombardy#2]
Hello Rinaldi, 
In the manuscript in medrxiv, Di,a,y ∼ Binomial (δa*θi,Ni,a,y), but in the code there is no θi multiplied for 2015-2019. I would also like to know the reason of choosing theta as a beta(3,2) distribution: it is not clear the relation between this choice and the reference to the newspaper article (ref. 15).
Thanks for the repository and reply.
Arnab

**Comment by gianlucaRinaldi** [comment]
Hi Arnab,

Thanks a lot for your comment! You're right, there is a typo in the manuscript (will fix it today, we are just updating the analysis with the most recent data). The formula in the code is right, θi is the infection rate from COVID so it is not relevant for years before 2020. 

Sorry we weren't clearer on how the article informed the prior, the idea was to have a diffuse prior with mean around 60% (the article says that a sample of people from one of the towns had 66% positive) so we just took a beta(3,2) because it's still quite diffuse but has a mean of .6.

**Comment by arnabbandyopadhyay** [comment]
Thanks for your quick reply. Another thing I would like to point out here is that: in function "model" it is 'theta_i[i]' (for 2020),  which I believe should be j, age group. Also, it is not clear to me why you are using demsData file which contains cities (eg: Bertonico) which are in excludedTown vector (see loadcleandata.R file).
Thank you again
Arnab

**Comment by gianlucaRinaldi** [comment]
Thanks to your comment I realized loadcleandata.R is a lot more complicated and confusing than it should be. I just updated the git with the most recent data and also made loadcleandata easier to follow. The formula in the model is correct, we assume all age groups have the same infection rate (theta_i, proportion of people infected) but that they might be different for different towns (maybe some had more people infected as a percentage of population.

Please let me know if it's still unclear!
